- build.gradle
- src/main/java/org/mjulikelion/engnews/authentication/AccessTokenProvider.java
- src/main/java/org/mjulikelion/engnews/authentication/AuthenticatedUser.java
- src/main/java/org/mjulikelion/engnews/authentication/AuthenticatedUserArgumentResolver.java
- src/main/java/org/mjulikelion/engnews/authentication/AuthenticationContext.java
- src/main/java/org/mjulikelion/engnews/authentication/AuthenticationExtractor.java
- src/main/java/org/mjulikelion/engnews/authentication/AuthenticationInterceptor.java
- src/main/java/org/mjulikelion/engnews/authentication/JwtEncoder.java
- src/main/java/org/mjulikelion/engnews/authentication/PasswordHashEncryption.java
- src/main/java/org/mjulikelion/engnews/config/AuthenticationConfig.java
- src/main/java/org/mjulikelion/engnews/config/CorsConfig.java
- src/main/java/org/mjulikelion/engnews/controller/AuthController.java
- src/main/java/org/mjulikelion/engnews/dto/request/LoginDto.java
- src/main/java/org/mjulikelion/engnews/dto/request/SignupDto.java
- src/main/java/org/mjulikelion/engnews/dto/response/ResponseDto.java
- src/main/java/org/mjulikelion/engnews/dto/response/TokenResponseDto.java
- src/main/java/org/mjulikelion/engnews/entity/BaseEntity.java
- src/main/java/org/mjulikelion/engnews/entity/User.java
- src/main/java/org/mjulikelion/engnews/repository/UserRepository.java
- src/main/java/org/mjulikelion/engnews/service/AuthService.java
- src/main/java/org/mjulikelion/engnews/service/CookieService.java
- src/main/java/org/mjulikelion/engnews/service/UserService.java
> Feature/#3 회원가입, 로그인, 로그아웃 구현

- src/main/java/org/mjulikelion/engnews/exception/BadRequestException.java
- src/main/java/org/mjulikelion/engnews/exception/ConflictException.java
- src/main/java/org/mjulikelion/engnews/exception/CustomException.java
- src/main/java/org/mjulikelion/engnews/exception/ErrorCode.java
- src/main/java/org/mjulikelion/engnews/exception/ForbiddenException.java
- src/main/java/org/mjulikelion/engnews/exception/NotFoundException.java
- src/main/java/org/mjulikelion/engnews/exception/UnauthorizedException.java
- src/main/java/org/mjulikelion/engnews/exception/ValidationException.java
- src/main/java/org/mjulikelion/engnews/exception/controller/ExceptionController.java
- src/main/java/org/mjulikelion/engnews/exception/dto/ErrorResponseDto.java
- src/main/java/org/mjulikelion/engnews/response/ResponseDto.java
예외 처리를 위한 Exception 작성
closed #2
> Feature/#2 Exception 설정

- src/main/java/org/mjulikelion/engnews/authentication/AccessTokenProvider.java
- src/main/java/org/mjulikelion/engnews/authentication/AuthenticationExtractor.java
- src/main/java/org/mjulikelion/engnews/authentication/AuthenticationInterceptor.java
- src/main/java/org/mjulikelion/engnews/authentication/JwtEncoder.java
- src/main/java/org/mjulikelion/engnews/exception/ErrorCode.java
- src/main/java/org/mjulikelion/engnews/service/UserService.java
> Feature/#7 에러 코드 추가

- src/main/java/org/mjulikelion/engnews/entity/ArticleLike.java
- src/main/java/org/mjulikelion/engnews/entity/BaseEntity.java
- src/main/java/org/mjulikelion/engnews/entity/Category.java
- src/main/java/org/mjulikelion/engnews/entity/Keyword.java
- src/main/java/org/mjulikelion/engnews/entity/User.java
- src/main/java/org/mjulikelion/engnews/entity/WordLike.java
- src/main/java/org/mjulikelion/engnews/entity/type/CategoryType.java
엔티티 생성
카테고리는 CategotyType에 enum타입으로 저장
close #5
> Feauret/#5 엔티티 생성

- src/main/java/org/mjulikelion/engnews/EngNewsApplication.java
- src/main/java/org/mjulikelion/engnews/config/AuthenticationConfig.java
- src/main/java/org/mjulikelion/engnews/controller/WordLikeController.java
- src/main/java/org/mjulikelion/engnews/dto/request/CreateWordLikeDto.java
- src/main/java/org/mjulikelion/engnews/dto/response/WordLikeListResponseData.java
- src/main/java/org/mjulikelion/engnews/dto/response/WordLikeResponseDto.java
- src/main/java/org/mjulikelion/engnews/exception/ErrorCode.java
- src/main/java/org/mjulikelion/engnews/repository/WordLikeRepository.java
- src/main/java/org/mjulikelion/engnews/service/WordLikeService.java
> Feature/#11 찜한 단어 기능 구현

- src/main/java/org/mjulikelion/engnews/config/AuthenticationConfig.java
- src/main/java/org/mjulikelion/engnews/controller/keywordController.java
- src/main/java/org/mjulikelion/engnews/dto/request/keyword/KeywordDto.java
- src/main/java/org/mjulikelion/engnews/dto/response/keyword/KeywordResponseDto.java
- src/main/java/org/mjulikelion/engnews/dto/response/keyword/KeywordsListResponseDto.java
- src/main/java/org/mjulikelion/engnews/exception/ErrorCode.java
- src/main/java/org/mjulikelion/engnews/repository/CategoryRepository.java
- src/main/java/org/mjulikelion/engnews/repository/KeywordRepository.java
- src/main/java/org/mjulikelion/engnews/service/KeywordService.java
카테고리 기능 구현
- [x ] KeywordRepository
close #15
> Feature/#15 키워드 기능 구현

- build.gradle
- src/main/java/org/mjulikelion/engnews/config/AuthenticationConfig.java
- src/main/java/org/mjulikelion/engnews/controller/NaverNewsController.java
- src/main/java/org/mjulikelion/engnews/repository/KeywordRepository.java
- src/main/java/org/mjulikelion/engnews/service/NaverNewsService.java
> Feature/#19 카테고리로 네이버 기사 목록 가져오기

- src/main/java/org/mjulikelion/engnews/config/AuthenticationConfig.java
- src/main/java/org/mjulikelion/engnews/controller/NaverNewsController.java
- src/main/java/org/mjulikelion/engnews/dto/request/article/CategoryRequestDto.java
- src/main/java/org/mjulikelion/engnews/dto/response/article/CategoryArticleDto.java
- src/main/java/org/mjulikelion/engnews/exception/ErrorCode.java
- src/main/java/org/mjulikelion/engnews/service/ArticleLikeService.java
- src/main/java/org/mjulikelion/engnews/service/NaverNewsService.java
> Feature/#25 네이버 기사 카테고리 별 크롤링

- src/main/java/org/mjulikelion/engnews/controller/UserController.java
- src/main/java/org/mjulikelion/engnews/dto/response/user/MypageDto.java
- src/main/java/org/mjulikelion/engnews/service/UserService.java
> Feature/#22 마이페이지 기능 구현

- src/main/java/org/mjulikelion/engnews/controller/CategoryController.java
- src/main/java/org/mjulikelion/engnews/dto/response/category/CategoryListResponseDto.java
- src/main/java/org/mjulikelion/engnews/dto/response/category/CategoryResponseDto.java
- src/main/java/org/mjulikelion/engnews/entity/Category.java
- src/main/java/org/mjulikelion/engnews/entity/type/CategoryType.java
- src/main/java/org/mjulikelion/engnews/service/CategoryService.java
> Feature/#29 카테고리 기능 로직 수정

- Dockerfile
- src/main/java/org/mjulikelion/engnews/controller/NaverNewsController.java
- src/main/java/org/mjulikelion/engnews/dto/request/article/ArticleRequestDto.java
- src/main/java/org/mjulikelion/engnews/dto/response/article/ArticleDto.java
- src/main/java/org/mjulikelion/engnews/service/ArticleLikeService.java
- src/main/java/org/mjulikelion/engnews/service/NaverNewsService.java
> Feature/#33 네이버 기사 단건조회

- src/main/java/org/mjulikelion/engnews/config/AuthenticationConfig.java
- src/main/java/org/mjulikelion/engnews/controller/CategoryController.java
> Feature/#35 API 명세서에 맞도록 형식 변경

- .github/workflows/gradle.yml
> Feature/#37 CI/CD 설정

- src/main/java/org/mjulikelion/engnews/controller/NYTNewsController.java
- src/main/java/org/mjulikelion/engnews/controller/NaverNewsController.java
- src/main/java/org/mjulikelion/engnews/service/NYTNewsService.java
- src/main/java/org/mjulikelion/engnews/service/NaverNewsService.java
카테고리 별 기사 조회 페이지네이션
Closes #45
> Feature/#45 카테고리 별 기사 조회 페이지네이션

- src/main/java/org/mjulikelion/engnews/dto/request/category/CategoryListDto.java
- src/main/java/org/mjulikelion/engnews/dto/response/category/CategoryListResponseDto.java
- src/main/java/org/mjulikelion/engnews/entity/Category.java
- src/main/java/org/mjulikelion/engnews/entity/CategoryOptions.java
- src/main/java/org/mjulikelion/engnews/repository/CategoryOptionsRepository.java
- src/main/java/org/mjulikelion/engnews/service/CategoryService.java
> Feature/#43 카테고리 옵션 엔티티 추가

- src/main/java/org/mjulikelion/engnews/config/AuthenticationConfig.java
- src/main/java/org/mjulikelion/engnews/controller/CategoryController.java
- src/main/java/org/mjulikelion/engnews/entity/CategoryOptions.java
- src/main/java/org/mjulikelion/engnews/service/CategoryService.java
> Feature/#51 뉴스 별 카테고리 목록 조회

- src/main/java/org/mjulikelion/engnews/config/AuthenticationConfig.java
- src/main/java/org/mjulikelion/engnews/controller/NYTNewsController.java
- src/main/java/org/mjulikelion/engnews/controller/NaverNewsController.java
- src/main/java/org/mjulikelion/engnews/service/NYTNewsService.java
- src/main/java/org/mjulikelion/engnews/service/NaverNewsService.java
> Feature/#53 top5 뉴스 불러오기

- src/main/java/org/mjulikelion/engnews/config/AuthenticationConfig.java
AuthenticationConfig경로 변경
close #57
> Feature/#57 AuthenticationConfig경로 수정 

- src/main/java/org/mjulikelion/engnews/config/AuthenticationConfig.java
- src/main/java/org/mjulikelion/engnews/controller/NaverNewsController.java
- src/main/java/org/mjulikelion/engnews/dto/response/article/RelatedArticleDto.java
- src/main/java/org/mjulikelion/engnews/service/NaverNewsService.java
> Feature/#62 네이버 뉴스 관련 기사 조회하기

- src/main/java/org/mjulikelion/engnews/config/AuthenticationConfig.java
- src/main/java/org/mjulikelion/engnews/controller/keywordController.java
- src/main/java/org/mjulikelion/engnews/dto/request/keyword/KeywordDto.java
- src/main/java/org/mjulikelion/engnews/dto/response/keyword/CategoryKeywordResponseDto.java
- src/main/java/org/mjulikelion/engnews/dto/response/keyword/KeywordOptionListResponseDto.java
- src/main/java/org/mjulikelion/engnews/dto/response/keyword/KeywordOptionResponseDto.java
- src/main/java/org/mjulikelion/engnews/dto/response/keyword/KeywordResponseDto.java
- src/main/java/org/mjulikelion/engnews/entity/Category.java
- src/main/java/org/mjulikelion/engnews/entity/CategoryOptions.java
- src/main/java/org/mjulikelion/engnews/entity/Keyword.java
- src/main/java/org/mjulikelion/engnews/entity/KeywordOptions.java
- src/main/java/org/mjulikelion/engnews/entity/User.java
- src/main/java/org/mjulikelion/engnews/repository/CategoryOptionsRepository.java
- src/main/java/org/mjulikelion/engnews/repository/KeywordOptionsRepository.java
- src/main/java/org/mjulikelion/engnews/service/KeywordService.java
- src/main/java/org/mjulikelion/engnews/service/NYTNewsService.java
- src/main/java/org/mjulikelion/engnews/service/NaverNewsService.java
> Feature/#64 키워드 조회 로직 변경

- src/main/java/org/mjulikelion/engnews/service/CookieService.java
> Feature/#66 로그인 유지 시간 변경

- src/main/java/org/mjulikelion/engnews/controller/ArticleLikeController.java
- src/main/java/org/mjulikelion/engnews/dto/request/articleLike/ArticleLikeDto.java
- src/main/java/org/mjulikelion/engnews/dto/request/articleLike/ArticleLikeUrlDto.java
- src/main/java/org/mjulikelion/engnews/entity/ArticleLike.java
- src/main/java/org/mjulikelion/engnews/repository/ArticleLikeRepository.java
- src/main/java/org/mjulikelion/engnews/service/ArticleLikeService.java
찜한 기사 뉴스 별 조회 로직 수정
Cloese #72
> Feature/#72 찜한 기사 뉴스 별 조회 로직 수정

- src/main/java/org/mjulikelion/engnews/controller/NYTNewsController.java
- src/main/java/org/mjulikelion/engnews/controller/NaverNewsController.java
- src/main/java/org/mjulikelion/engnews/service/NYTNewsService.java
- src/main/java/org/mjulikelion/engnews/service/NaverNewsService.java
> Feature/#74 기사 정렬 기능 추가

- src/main/java/org/mjulikelion/engnews/controller/NYTNewsController.java
- src/main/java/org/mjulikelion/engnews/repository/ArticleLikeRepository.java
> Hotfix/#76 Build 오류 해결

- src/main/java/org/mjulikelion/engnews/config/AuthenticationConfig.java
- src/main/java/org/mjulikelion/engnews/controller/TranslateController.java
- src/main/java/org/mjulikelion/engnews/dto/ai/E2kResponseDto.java
- src/main/java/org/mjulikelion/engnews/dto/ai/E2kTranslateDto.java
- src/main/java/org/mjulikelion/engnews/service/TranslateService.java
> Feature/#78 ML /영어 → 한글로 통번역 AI 연결

- src/main/java/org/mjulikelion/engnews/config/AuthenticationConfig.java
- src/main/java/org/mjulikelion/engnews/controller/TranslateController.java
- src/main/java/org/mjulikelion/engnews/dto/ai/TranslateDto.java
- src/main/java/org/mjulikelion/engnews/service/TranslateService.java
/translate API연결
- [] AuthenticatedUser
close #79
> Feature/#79 ML translate API연결

- src/main/java/org/mjulikelion/engnews/config/AuthenticationConfig.java
- src/main/java/org/mjulikelion/engnews/controller/TranslateController.java
- src/main/java/org/mjulikelion/engnews/dto/ai/K2eResponseDto.java
- src/main/java/org/mjulikelion/engnews/dto/ai/K2eTranslateDto.java
- src/main/java/org/mjulikelion/engnews/service/TranslateService.java
> Feature/#80 ML /한글 → 영어로 통번역 AI 연결

- src/main/java/org/mjulikelion/engnews/controller/CategoryController.java
- src/main/java/org/mjulikelion/engnews/dto/response/category/CategoryInfoDto.java
- src/main/java/org/mjulikelion/engnews/dto/response/keyword/KeywordOptionDto.java
- src/main/java/org/mjulikelion/engnews/service/CategoryService.java
> Feature/#87 키워드 로직 수정

- src/main/java/org/mjulikelion/engnews/service/NaverNewsService.java
> Feature/#92 관련 기사 오류 수정

- src/main/java/org/mjulikelion/engnews/controller/KeywordController.java
- src/main/java/org/mjulikelion/engnews/controller/NYTNewsController.java
- src/main/java/org/mjulikelion/engnews/repository/KeywordRepository.java
- src/main/java/org/mjulikelion/engnews/service/ArticleLikeService.java
- src/main/java/org/mjulikelion/engnews/service/KeywordService.java
- src/main/java/org/mjulikelion/engnews/service/NYTNewsService.java
- src/main/java/org/mjulikelion/engnews/service/NaverNewsService.java
- src/main/java/org/mjulikelion/engnews/service/WordLikeService.java
> Refactor/#94 코드 리팩터링

- src/main/java/org/mjulikelion/engnews/service/NYTNewsService.java
> Bug/#96 getNYTByCategory 서비스 로직 변경

- src/main/java/org/mjulikelion/engnews/service/NYTNewsService.java
리팩토링 브랜치 위에 카테고리 로직 변경
close #98
> Bug/#98 getNYTByCategory 서비스 로직 변경

- src/main/java/org/mjulikelion/engnews/repository/KeywordRepository.java
- src/main/java/org/mjulikelion/engnews/service/KeywordService.java
> Hotfix/#100 키워드 삭제 로직 수정

- src/main/java/org/mjulikelion/engnews/service/ai/AnalyzeService.java
- src/main/java/org/mjulikelion/engnews/service/ai/SummarizeService.java
- src/main/java/org/mjulikelion/engnews/service/ai/TranslateService.java
> Feature/#104 ML주소 변경 반영

- src/main/java/org/mjulikelion/engnews/config/AuthenticationConfig.java
- src/main/java/org/mjulikelion/engnews/controller/ai/SummarizeController.java
- src/main/java/org/mjulikelion/engnews/controller/ai/TranslateController.java
- src/main/java/org/mjulikelion/engnews/dto/ai/request/TrySummarizeContentDto.java
- src/main/java/org/mjulikelion/engnews/dto/ai/request/TrySummarizeMessageDto.java
- src/main/java/org/mjulikelion/engnews/dto/ai/request/TryTranslateMessageDto.java
- src/main/java/org/mjulikelion/engnews/dto/ai/request/TryTranslateSentenceDto.java
- src/main/java/org/mjulikelion/engnews/service/ai/SummarizeService.java
- src/main/java/org/mjulikelion/engnews/service/ai/TranslateService.java
번역시도하기/ 요청 시도하기 를 각각 첫번재 통신일 떼와 두번째 이상 통신일 때는 나눠서 요청하도록 분리
> Feature/#106 번역/요약 요청 분리

- src/main/java/org/mjulikelion/engnews/service/ai/TranslateService.java
> Refactor/#109 응답 메세지 처리 수정

- src/main/java/org/mjulikelion/engnews/service/ai/SummarizeService.java
> Refactor/#112 응답 메세지 처리 수정2

- src/main/java/org/mjulikelion/engnews/service/NYTNewsService.java
> Feature/#116 nyt 기본 이미지 변경
